/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sofa1-mod.gltf -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    BackCushion002: THREE.Mesh;
    CouchBase: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube002: THREE.Mesh;
    BackCushion001: THREE.Mesh;
    BackCushion: THREE.Mesh;
    Legs: THREE.Mesh;
    SeatCushion: THREE.Mesh;
    SeatCushion001: THREE.Mesh;
    SeatCushion002: THREE.Mesh;
    SideCushion: THREE.Mesh;
    SideCushion001: THREE.Mesh;
    YellowCushion1: THREE.Mesh;
    YellowCushion2: THREE.Mesh;
  };
  materials: {
    Cloth1: THREE.MeshStandardMaterial;
    Cloth2: THREE.MeshStandardMaterial;
    StainlessSteel: THREE.MeshStandardMaterial;
    Cloth: THREE.MeshStandardMaterial;
    WhiteCloth: THREE.MeshStandardMaterial;
  };
  // @ts-ignore
  animations: GLTFAction[];
};

// @ts-ignore
export default function Model(props: JSX.IntrinsicElements["group"]) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/models/sofa1-mod.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material}>
        <mesh
          geometry={nodes.BackCushion002.geometry}
          material={materials.Cloth}
        />
        <mesh geometry={nodes.CouchBase.geometry} material={materials.Cloth} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Cloth} />
        <mesh geometry={nodes.Cube002.geometry} material={materials.Cloth} />
        <mesh
          geometry={nodes.BackCushion001.geometry}
          material={materials.Cloth}
        />
        <mesh
          geometry={nodes.BackCushion.geometry}
          material={materials.Cloth}
        />
        <mesh
          geometry={nodes.Legs.geometry}
          material={materials.StainlessSteel}
        />
        <mesh
          geometry={nodes.SeatCushion.geometry}
          material={materials.Cloth}
        />
        <mesh
          geometry={nodes.SeatCushion001.geometry}
          material={materials.Cloth}
        />
        <mesh
          geometry={nodes.SeatCushion002.geometry}
          material={materials.Cloth}
        />
        <mesh
          geometry={nodes.SideCushion.geometry}
          material={materials.Cloth}
        />
        <mesh
          geometry={nodes.SideCushion001.geometry}
          material={materials.Cloth}
        />
        <mesh
          geometry={nodes.YellowCushion1.geometry}
          material={materials.WhiteCloth}
        />
        <mesh
          geometry={nodes.YellowCushion2.geometry}
          material={materials.WhiteCloth}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/sofa1-mod.gltf");
